export default class JSONFeed {

  data() {
    return {
      permalink: "/feed.json",
      eleventyExcludeFromCollections: true,
    }
  }

  render(data) {
    const feed = {
      version: "https://jsonfeed.org/version/1",
      title: data.site.title,
      home_page_url: data.site.url,
      feed_url: new URL(this.data().permalink, data.site.url),
      description: data.site.description,

      // This is the URL of the 512 favicon generated by eleventy-plugin-gen-favicons, which is the reccomended size.
      icon: new URL("/icon-512.png", data.site.url),
      author: {
        name: data.schema.author?.name,
        url: data.schema.author?.url,
        avatar: data.schema.author?.image
      },
      items: [],
    };

    for (const item of data.collections.project) {
      const url = new URL(item.url, data.site.url);
      feed.items.push({
        id: url,
        title: item.data.title ?? "Untitled",
        url,
        content_html: item.templateContent ?? item.data.content ?? "FIXME: No content",
        summary: item.data.summary ?? item.data.description ?? undefined,
        // FIXME: hero image is processed by eleventy-img, but not available in the data.
        // image: item.data.hero.src,
        // banner_image: item.data.banner.src
        date_published: item.date.toISOString(),
        date_modified: item.date.toISOString(),
        author: {
          name: data.schema.author?.name,
          url: data.schema.author?.url,
          avatar: data.schema.author?.image
        },
        tags: item.data.tags ?? [],
        // TODO: add support for attachements (aka podcasts)
        // attachments: item.data.attachments ?? [],

      });
    }
    return JSON.stringify(feed);
  }
}